In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation
from tensorflow.keras.optimizers import Adam

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
x_train = pd.read_csv("/content/drive/MyDrive/DataForCheckpoint2/DataForCheckpoint2/Voltage_L1_train.csv")
x_test = pd.read_csv("/content/drive/MyDrive/DataForCheckpoint2/DataForCheckpoint2/Voltage_L1_test.csv")
y_train = pd.read_csv("/content/drive/MyDrive/DataForCheckpoint2/DataForCheckpoint2/output_train.csv")
y_test = pd.read_csv("/content/drive/MyDrive/DataForCheckpoint2/DataForCheckpoint2/output_test.csv")

In [4]:
header =[]
for i in range(1,x_train.shape[1]+1):
    header.append("Col"+str(i))
x_train.columns = header
x_test.columns = header

In [5]:
x_train.head()

          Col1         Col2         Col3  ...       Col254       Col255       Col256
0   573.652486  1003.343736  1588.404525  ... -1282.042025  -601.968217  -156.848367
1  4757.365183  5264.598912  5428.642486  ...  3619.932691  4008.288701  4422.229911
2  4242.144824  4644.679402  5013.356532  ...  2776.876479  3248.638662  3807.665149
3  2077.819247  2561.679246  3085.653813  ...   304.222722   935.528504  1460.127297
4  3599.645319  4099.944762  4499.282469  ...  2002.557438  2576.468343  3036.303600

[5 rows x 256 columns]

In [6]:
x_test.head()

          Col1         Col2         Col3  ...       Col254       Col255       Col256
0  4216.164293  4550.919227  4885.253969  ...  2729.066018  3292.437301  3770.985050
1   795.638794  1340.736614  1928.805243  ...  -970.063115  -413.973048   202.507328
2  1220.943267  1770.550513  2318.816674  ...  -553.276475    43.863168   614.870963
3  1013.772210  1621.783618  2178.146635  ...  -704.032900  -188.518269   466.064827
4  4490.355896  4862.601717  5235.681699  ...  3069.781180  3624.993700  4116.325633

[5 rows x 256 columns]

In [7]:
y_train.tail()

      1
5994  6
5995  6
5996  6
5997  6
5998  6

In [8]:
y_test.head()

   1
0  1
1  1
2  1
3  1
4  1

In [11]:
sum(x_train.apply(lambda x: sum(x.isnull().values), axis = 1)>0)

0

In [12]:
print("x_train",x_train.shape)
print("y_train",y_train.shape)
print("x_test",x_test.shape)
print("y_test",y_test.shape)

x_train (5999, 256)
y_train (5999, 1)
x_test (3599, 256)
y_test (3599, 1)

In [36]:
from sklearn.ensemble import RandomForestClassifier

modelR = RandomForestClassifier(90) 



# fit the model

modelR.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  if __name__ == '__main__':

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=90,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [37]:
predict_testR=modelR.predict(x_test)
predict_testR

array([1, 1, 1, ..., 6, 6, 6])

In [38]:
from sklearn.metrics import accuracy_score

accuracy_test=accuracy_score(y_test,predict_testR)
accuracy_test

0.9121978327313143

In [39]:
from sklearn.naive_bayes import GaussianNB 

modelN = GaussianNB() 

modelN.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GaussianNB(priors=None, var_smoothing=1e-09)

In [40]:
predict_testN=modelN.predict(x_test)
predict_testN

array([1, 3, 3, ..., 6, 6, 6])

In [41]:
accuracy_test=accuracy_score(y_test,predict_testN)
accuracy_test

0.811058627396499

In [9]:
from sklearn.svm import SVC 


modelS = SVC()  
modelS.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [11]:
predict_testS=modelS.predict(x_test)
predict_testS

array([1, 3, 3, ..., 6, 6, 6])

In [13]:
from sklearn.metrics import accuracy_score

accuracy_test=accuracy_score(y_test,predict_testS)
accuracy_test

0.8421783828841345